### ISSUE TITLE
how to solve"Couldn't find file: myfilename_output_kmc_canon.kmc_pre"

### ISSUE THREAD

**Issue by jiangjiayi1018** [voichek/kmersGWAS#153] opened 2024-08-06 09:37 UTC
I am deeply confused about the description of "Couldn't find file: myfilename_output_kmc_canon.kmc_pre", after running kmc for the second time.This error has prevented me from continuing my kmer analysis for a long time. Thank you in advance.
<img width="460" alt="屏幕截图 2024-08-06 173444" src="https://github.com/user-attachments/assets/3ff7e905-42a9-43ed-9c5c-d1bebbfec56a">

**Comment by voichek** [comment] 2024-08-06 09:49
Dear Jian (?),

Thank you for your interest in our library! 

To help us better assist you, please provide as much detail as possible about the issue you're encountering. This includes the specific code you're running, any relevant files, and the exact error message or behavior you are experiencing.

As a first troubleshooting step, we recommend running the E. coli example included with our library. This example is designed to work in a standard environment and can help determine whether the issue is related to your setup or the way the code is being executed.

Best,
Yoav

**Comment by jiangjiayi1018** [comment] 2024-08-09 05:59
> Dear Jian (?),
> 
> Thank you for your interest in our library!
> 
> To help us better assist you, please provide as much detail as possible about the issue you're encountering. This includes the specific code you're running, any relevant files, and the exact error message or behavior you are experiencing.
> 
> As a first troubleshooting step, we recommend running the E. coli example included with our library. This example is designed to work in a standard environment and can help determine whether the issue is related to your setup or the way the code is being executed.
> 
> Best, Yoav

The object of my operation is the sequencing data of a certain variety of tomato, I followed your manual.pdf tutorial on individual_X to perform two kmc work and successfully output the output file, but when I perform the step of kmers_add_strand_information, the system shows that it cannot find the file The file "output_kmc_canon.kmc_pre" is not found.
<img width="977" alt="屏幕截图 2024-08-09 135832" src="https://github.com/user-attachments/assets/0c13a7d8-dbb3-4141-958d-f572cf48edb4">

**Comment by voichek** [comment] 2024-08-10 17:44
It is because the filename is without `output_`.

If you have other problems, as I said before, please make sure you can run the e. coli example first.

**Comment by voichek** [comment] 2024-08-19 08:45
I am closing this issue, please reopen if needed.

**Closed by voichek** 2024-08-19 08:45 UTC
