### ISSUE TITLE
kmer_to_use

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#58] opened 2020-09-02 00:24 UTC
Dear Author
My data is six batches, each containing at least 90 individuals,When I put these six batches of individuals together, there were 665 individuals,I ran the code that generated the kmer_to_use, and it turns out that this picture:
![image](https://user-images.githubusercontent.com/58722433/91918170-be790900-ecf4-11ea-818d-eb1889a8d583.png)
And when I run each batch apart kmer_to_use, it will generate each batch kmer_to_use,This problem arises above when running together.what should I do?
And even more odd,My colleagues run more than 800 individuals together to run out, why not me more than 600 individuals

**Comment by duhuipeng** [comment] 2020-09-04 00:10
Dear author
I separate more than 600 individuals into different batches to run, each batch to run can be generated kmer_to_use, but when I put all the individuals together to run, I can not run out, will report a fatal error(above)
I'd like to ask you how I can integrate these different batches of kmer_to_use into a total kmer_to_use
Looking forward to your reply

**Comment by voichek** [comment] 2020-09-07 11:49
Hi,

Sorry for the late response, I was on holiday.

1. I would need to debug this, do you think it is possible to share the kmers files (I know it must be huge)?
2. Does it always fall in the same line ?
3. Did you compile it yourself?

Yoav

**Comment by voichek** [comment] 2020-09-10 18:11
Can you please answer the questions I asked you before.

Did you change the code? What does it mean run manually?

**Comment by duhuipeng** [comment] 2020-09-11 00:13
I didn't change any code and run manually
This is the code I ran
/home/Duhuipeng/LZF/kmers_proj/KMC/bin/list_kmers_found_in_multiple_samples -l kmers_list_paths.txt -k 31 --mac 5 -p 0.2 -o kmers_to_use
 It will run to the graph I  just intercepted without any error information, and end at line 3770

**Comment by voichek** [comment] 2020-09-11 14:28
Dear Tom,

First, you are now raising a new issue. If the previous issue is solved, please close this issue thread and open a new one with this new problem you have.
I will just note that I am surprised by this new error you report, as there is a for loop in the program which runs from 1 to 5000, so the fact it stops in the middle without any error message is extremely peculiar.

Regarding the first problem you asked about, you still did not answer all my first questions. If you want me to help you you need to be more cooperative. 

I will happily help, but I need you to provide the needed detail. Also, due to the nature of the problem you reported I will likely need to get the files used to run the program so I can rerun it on my system and see if it also fails here and then debug it. 

Best wishes,
Yoav

**Comment by duhuipeng** [comment] 2020-09-11 14:57
Dear author
 Because this data is laboratory, I have no authority to share it,Because I've been showing up questions for screenshots, First I thought it was my data problem,However, when I split the data into several different file directories to run, kmer_to_use under each directory normal output, So at this point I don't think it's a data problem.
So I'd like to ask, do you know how I can integrate the files (kmer_to_use)in each directory to generate a total file(kmer_to_use)

**Comment by duhuipeng** [comment] 2020-09-11 15:03
And my data file is very large, up to 11 T, sharing should also be difficult to operate, and I do not have the authority to share with you,Because this data is laboratory,Managed by mentors.
![image](https://user-images.githubusercontent.com/58722433/92941206-a9357480-f482-11ea-8e28-f7caf7f83bad.png)
 This is the total (line 3770 is closed without any errors)
![image](https://user-images.githubusercontent.com/58722433/92941331-d1bd6e80-f482-11ea-8b76-0c03a82ea6ea.png)
Here is how I divide the total into several directories, where the output kmer_to_use is normal(Up to 5000 rows)

**Comment by voichek** [comment] 2020-09-11 16:42
Dear Tom,

1. This screenshot does not help. 
2. I would recommend against the patches that you suggest. First, if you have an error, it might mean that something else is wrong and this need to be solved. Second, there is filtering step which needs the full population so results will be different. 
If you still want to merge, you can learn from the code the binary coding of the files and do it on your own risk, I can not support this functionality.
* In any of my many used for me and for others non of this errors accord for much larger datasets. So the problem is not in your data but probably in your system setup.

3. To try and be productive please answer the following, in this order
A) Is the "segmentation error" now changed to stop in line 3770? If so what did you change?
B) What are the size of the genome (more or less) of this 665 individuals? Is it similar to Arabidopsis?
C) Did you run successfully the E. coli example? 

Best,
Yoav

**Comment by voichek** [comment] 2020-09-18 08:11
Dear Tom,

As you are not answering I am closing this issue.
In case you want to keep discussing reopen it with response to my questions.

Yoav

**Closed by voichek** 2020-09-18 08:11 UTC
