### ISSUE TITLE
problemes with kmers_add_strand_information

### ISSUE THREAD

**Issue by dosshra** [voichek/kmersGWAS#155] opened 2024-08-25 06:49 UTC
Hello
I am running the following SLRUM script on HPC:
```bash
#!/bin/sh
#SBATCH --job-name=kmermono
#SBATCH --time=1-00:00:00
#SBATCH --mem=250g
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=60
#SBATCH --array=6,8
#SBATCH --partition=hive1d

cd datafolder

SAMP=$(sed -n "${SLURM_ARRAY_TASK_ID}p" samplist)

mkdir ${SAMP}
mv *${SAMP}*gz ${SAMP}/

cd ${SAMP}

ls *.gz >filelist

echo 1
~/kmergwas/external_programs/kmc_v3 -t2 -k31 -ci2 @filelist output_kmc_canon ./ 1> kmc_canon.1 2> kmc_canon.2

echo 2
~/kmergwas/external_programs/kmc_v3 -t2 -k31 -ci0 -b @filelist output_kmc_all ./ tmp 1> kmc_all.1 2>kmc_all.2

echo 3
~/kmergwas/bin/kmers_add_strand_information -c output_kmc_canon -n output_kmc_all -k 31 -o kmers_with_strand

echo 4
```

For 7 of of the jobs the script runs smoothly with no problems but for 2 of the jobs I get this:

>1
2
3
kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, long unsigned int>; Key = long unsigned int; HashFcn = Hash64; ExtractKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SelectKey; SetKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, long unsigned int> >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.
/var/spool/slurm/slurmd/job785837/slurm_script: line 23: 2189333 Aborted                 (core dumped) ~/kmergwas/bin/kmers_add_strand_information -c output_kmc_canon -n output_kmc_all -k 31 -o kmers_with_strand
4
  
The size of the files is:   88G output_kmc_all.kmc_suf ,  29G output_kmc_canon.kmc_suf 
Thank you

**Comment by voichek** [comment] 2024-08-30 10:02
Hi,

It looks like the issue might be due to insufficient memory. To help pinpoint the problem, I suggest running a single job on its own to check if it still fails. If the 250GB of memory is shared across all runs, it could lead to memory exhaustion, causing the job to fail.

The total size of all files may not be the only factor; what matters is the memory required to process each specific sample. Please try running the script with only one sample and provide its size, along with details on how much memory is needed for that single run.

This will help us better understand if the issue is related to memory limits.

Best,
Yoav

**Comment by voichek** [comment] 2024-09-09 08:05
Hi,

Can we close this issue?

Best, Yoav

**Comment by dosshra** [comment] 2024-09-09 08:32
Yes, Thank you, 
Using a node with 700GB of RAM solved the problem.

**Comment by voichek** [comment] 2024-09-09 08:34
OMG, sounds a bit excessive. 

But as long as it works.
Best,
Yoav

**Closed by voichek** 2024-09-09 08:34 UTC
